data:
  dataset_path: 'datasets'

  aida_yago2_path: 'datasets/AIDA-YAGO2-dataset.tsv'
  yago4_facts_path: 'datasets/yago-wd-facts.nt.gz'
  yago4_labels_path: 'datasets/yago-wd-labels.nt.gz'

  node_path: 'graph_yago_nodes.feather'
  edge_path: 'graph_yago_edges.feather'
  rel_path: 'graph_yago_rels.feather'
  pyg_path: 'graph_yago.safetensors'